mendix/native-template

README.md
=> [NALM-194] Add a reminder to add the native-packager flag

android/app/build.gradle, android/app/src/main/java/com/mendix/nativetemplate/MainApplication.java, android/build.gradle, android/settings.gradle, ios/AppDelegate.m
*Android*
- Drop a `google-services.json` file into the `android/app` directory
*iOS*
- Open the workspace in Xcode and drop the `GoogleService-Info.plist` file into the root (ie `ios`) directory
- Make sure to check the `Copy items if needed` option
- Use the `Create Group` option
- And select both targets ie `nativeTemplate` and `dev`
=> [NALM-196] Introduce Firebase and GoogleServices

android/app/build.gradle, android/app/src/main/java/com/mendix/nativetemplate/MainApplication.java, android/settings.gradle, ios/Podfile, ios/Podfile.lock, package-lock.json, package.json
As the core one is deprecated.
=> Add new datetimepicker library

ios/Podfile, ios/Podfile.lock, ios/nativeTemplate.xcodeproj/project.pbxproj
With the RN upgrade we slipped in some features for the camera that require Firebase on iOS. 
With this we are getting rid of them.
=> Remove features that require MLKit and Firebase

android/gradle.properties
Fixing Gradle OutOfMemory issues on fairly sized projects
=> Max out gradle memory availability

android/app/build.gradle, ios/Config/config.xcconfig
Reverts mendix/native-template#107 as it breaks Java compilation due to take keyword
=> Revert "Update bundle ids"

ios/Podfile.lock, package-lock.json, package.json
=> Upgrade datetimepicker to v3.0.0

ios/Podfile.lock, package-lock.json, package.json
Reverts mendix/native-template#123
=> Revert "Upgrade datetimepicker to v3.0.0"

capabilities-setup-config.json, capabilities.json, ios/nativeTemplate/Info.plist
This ties in with the NBUI MR with same title.
=> [NALM-845] Support for maps capability

android/app/src/main/AndroidManifest.xml, package-lock.json, package.json
- Added legacy storage support to Android
=> Prepare release 4.2.3

android/app/src/main/AndroidManifest.xml, package-lock.json, package.json
- Added legacy storage support to Android
=> Prepare 5.0.5 release

ios/Config/config.xcconfig, ios/Dev/Config/config.xcconfig, ios/nativeTemplate.xcodeproj/project.pbxproj
=> [NALM-1273] Introduce iOS bundle name

package-lock.json, package.json, react-native.config.js
Two bugs:
- In android if videoplayer is in scrollview, controls sticks and does not follow the video player
- In android some video's cannot load
We specify the player in react native config.json.
=> Switch to Exoplayer

appcenter-build-config.json, appcenter-post-clone.sh, appcenter-pre-build.sh, package.json
- Include toolkit dependency 
- Introduce Toolkit Configure step to AppCenter pre-build script
- Fail early on any AppCenter script exception
=> Introduce toolkit support to 5.1.x

android/app/src/dev/java/com/mendix/nativetemplate/MainActivity.java, android/build.gradle, capabilities-setup-config.json, ios/AppDelegate.h, ios/AppDelegate.m, ios/Dev/AppDelegate.h, ios/Dev/AppDelegate.m, ios/MendixAppDelegate.h, ios/mendix_utils.rb, ios/nativeTemplate.xcodeproj/project.pbxproj
iOS changes would need to be cherry-picked into the other version tracks
=> [MOO-48] Handle deep links in developer app 

ios/Podfile
- Include proper check for versions greater than 12.5
=> [MOO-241] Introduce Xcode 12.5 react-native bridge-module patch

android/app/build.gradle, android/app/src/dev/java/com/mendix/nativetemplate/MainActivity.java, package-lock.json
=> [MOO-315] Update okhttp library

android/app/build.gradle, android/app/src/dev/java/com/mendix/nativetemplate/MainActivity.java, package-lock.json
=> [MOO-315] Updated okhttp library

capabilities-setup-config.json, capabilities.android.json, capabilities.ios.json, ios/crashlytics-config.sh, patches/react-native-firebase+5.6.0.patch
=> [MOO-304] Crashlytics capability support

package-lock.json, package.json
- Support for firebase crashlytics
=> Release v5.2.2

package-lock.json, package.json
- Support for firebase crashlytics
=> Release v5.1.15

package-lock.json, package.json, patches/@react-native-community+cameraroll+4.0.1.patch
Add patch for react-native-community/cameraroll v4.0.1 to add filestorage support for android 30
Tested on API 28 / 29 / 30
See [JIRA story](https://mendix.atlassian.net/browse/NC-516) for test project
=> [NC-516] Add filestorage support for android 30

ios/Podfile.lock, package-lock.json, package.json, patches/@react-native-community+cameraroll+4.0.1.patch
Add patch for react-native-community/cameraroll v4.0.1 to add filestorage support for android 30 in Mendix 8
Tested on 
Android API 28 / 29 / 30
iOS 15
=> [NC-516] Add filestorage support for android 30 Mx8

ios/AppDelegate.m, ios/Dev/AppDelegate.m
Only clear key chain if the app is freshly installed.
=> [MOO-490] Clear keychain only when it's a fresh install

package-lock.json, package.json
Upgrade the `@react-native-community/datetimepicker` version to 3.5.2
=> [NC-379] Date picker not visible in dark mode

package-lock.json, package.json
=> fix: update react-native-vector-icons dependency

package-lock.json, package.json
=> fix: update react-native-vector-icons dependency [6.2.0]

.github/workflows/linux-test-npm-installation-latest-node.yml, package-lock.json, package.json
Adds compatibility to latest node using overrides (npm 7+) and resolutions (yarn).
=> [MOO-676] Fix npm dependencies using node 18 and npm 8

package-lock.json, package.json
update react-native-permission to use the latest available device permissions for IOS and Android
=> update react native permissions library

android/build.gradle
Fixes the version of react-native being automatically updated due to https://github.com/facebook/react-native/issues/35210
=> [MOO-820] Fix android build

android/app/build.gradle
**Solved:** M1 Unknown host CPU architecture: arm64
=> feat: allow to build android app for m1 user (apple silicon)

ios/Podfile, patches/react-native+0.61.5.patch
NOTE: iOS Build fails due to certificate issue, this is gonna be fixed in another PR
=> [MOO-1053] Fix build issue in AppCenter

CHANGELOG.md, android/app/src/appstore/java/com/mendix/nativetemplate/MainActivity.java, android/app/src/main/java/com/mendix/nativetemplate/MainApplication.java, android/app/src/main/res/values/styles.xml, package-lock.json, package.json
On Android devices, the native app splash screen is distorted in landscape mode, logo is stretched horizontally, or squashed vertically.
Steps:
1. Ensure the Android device is in portrait mode.
2. Launch the custom dev app.
3. Scan or type the URL to load the Mendix app.
4. Observe the splash screen.
**Expected Result:** The logo in the splash screen should be displayed correctly without any distortion. 
Steps:
1. Rotate the Android device to landscape mode.
2. Launch the custom dev app.
3. Scan or type the URL to load the Mendix app.
4. Observe the splash screen.
**Expected Result:** The logo in the splash screen should be displayed correctly without any distortion, stretching, or squashing.
Steps:
1. Ensure the Android device is in portrait mode.
2. Launch the custom dev app.
3. Scan or …
=> [MOO-1043]: Native app splash screen is distorted on Android in landscape mode

android/app/build.gradle, android/app/src/main/java/com/mendix/nativetemplate/MainApplication.java, android/settings.gradle, appcenter-pre-build.sh, capabilities-setup-config.json, ios/nativeTemplate/Info.plist, package-lock.json, package.json, react-native.config.js
Testing notes:
Mendix OTA should still working as expected.
Apps should still work properly
DevApps should be working properly
=> [MOO-1009] Remove react-native-code-push

.github/workflows/android-build-custom-dev-app.yml, CHANGELOG.md, package-lock.json, package.json, patches/react-native-push-notification+8.1.1.patch
Prevent crash for local notifications on Android 14 and add check exact alarm permission lib
=> [MOO-1361] Add patch to push notifications and add rn-schedule-exact-alarm (9.24)

.github/workflows/ios-build-custom-dev-app.yml, android/build.gradle
tested with nmr project on sp 10.12
=> MOO 1692 - Update Minimum SDK Version to 23 for Native Template 8 and Below - 8.2.x

.github/workflows/ios-build-custom-dev-app.yml, android/build.gradle
tested with nmr project on sp 9.24.26
=> MOO 1692 - Update Minimum SDK Version to 23 for Native Template 8 and Below - 7.x.x

CHANGELOG.md
We have updated min sdk to 23 on android
=> update: changelog min sdk 23

android/app/src/appstore/java/AndroidManifest.xml, android/app/src/dev/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml
- **Link to release note:** [https://github.com/mendix/docs/pull/9176]
_..._
=> MOO[1633] adding fontScale to configChanges prevents crashinga

.github/pull_request_template.md, .github/workflows/check-docs-pr.yml
=> [MOO-1833]: Add docs PR check workflow

.github/workflows/release-it.yml
=> Replace admin token with github token

.github/workflows/release-it.yml
=> Fix pipeline

package-lock.json, package.json
=> MOO-1932 Remove netinfo dependancy

package-lock.json, package.json
=> M00-1932 remove netinfo dependancy

.github/workflows/release-it.yml, package-lock.json, package.json
=> Fix release action 11.x
