- android/app/src/main/AndroidManifest.xml
Currently, we need to explicitly define all the required permissions.
> Adding missing permissions required by Mendix

- android/app/src/main/res/values/styles.xml
This fix was introduced to the Make it Native more than a year ago and for a reason. Therefore, it also has to be part of the Native Template. As a side-effect it solves the problem with the different height of text inputs between the Native Template and Make it Native.
> Fix a bug where editext underline might crash the app when trying to set a background drawable

- .gitignore
This is important when building locally using a private repository.
> Exclude node_modules only at the toplevel because ios bundle also contains node_modules, which should not be excluded

- package-lock.json
- package.json
The previous v5.0.3 release contained elements from the pre-release version of the template meant for the UI. This PR remedies that users on the CLI can not at this moment build apps requiring push notifications without setting the toggle to true.
> Cherry-pick only required updates to the stable release

- android/app/src/main/AndroidManifest.xml
Out of google's docs: 
`If your app targets Android 10 (API level 29), opt-out of scoped storage and continue using the approach for Android 9 and lower to perform this operation.`
> Enable legacy storage to support Android 10/11

- ios/Podfile.lock
The Podfile.lock on master is pulling wrong version for Firebase. Updating to the correct version.
> Revert podfile.lock updates

- patches/react-native-firebase+5.6.0.patch
This patch is only relevant because the team behind the popular firebase library has discontinued support for `v5.x`. It is resolved in `v6.x`.
See https://github.com/invertase/react-native-firebase/issues/3944
EDIT:
This bug found its way into https://github.com/react-native-push-notification-ios/push-notification-ios. A patch for that would come in another PR for the v6.x track while this can go in for the v5.x track.
https://github.com/mendix/native-template/pull/158
cc @stmarkidis @diego-antonelli
> Introduce Firebase main thread patch

- package.json
Avoid possible mistakes if npm install hasn't run yet.
> [NALM-1164] Include no-install flags for npx commands

- android/app/src/main/AndroidManifest.xml
Adjust resize can mess with the scrollview's children blur/focus  behaviour. This should alleviate the issue as it would default in panning the view instead of resizing the viewport.
> [NALM-1250] Default to adjustPan for soft keyboard

- appcenter-post-clone.sh
- appcenter-pre-build.sh
This makes sure when either of the scripts fail, it causes App Center build to fail early
> Make App Center scripts to fail early

- ios/mendix_utils.rb
This PR extends the capabilities setup configuration to support adding phases during iOS build. Supports only scripts for now.
Registered as `buildPhases`. Example below.
```typescript
{
name: string;
path: string;
execution_position: 'before_compile' | 'after_compile';
input_files: Array<string>;
}
```
```json
"capability": {
"ios": {
"buildPhases": [
{
"name": "Run Script",
"path": "./iOS/script.sh",
"execution_position": "after_compile",
"input_files": [
"$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"
]
}
]
}
}
```
> Introduce iOS capability support for script phases

- capabilities-setup-config.json
- capabilities.android.json
- capabilities.ios.json
- ios/crashlytics-config.sh
- patches/react-native-firebase+5.6.0.patch
- Split `pushNotifications` capability into `firebaseIos` and `firebaseAndroid`. This breaks support for CLI-based apps.
- Introduce `crashlytics` capability configuration
> [MOO-304] Crashlytics capability support

- android/app/src/main/AndroidManifest.xml
For Android 11+ package visibility was introduced https://developer.android.com/training/package-visibility; this limits the visible app the application gets access to. 
As documented https://reactnative.dev/docs/linking#canopenurl a query tag needs to be added to the AndroidManifest.xml
> [MOO-396] Add missing query parameter

- android/app/src/main/AndroidManifest.xml
Android 11 requires the Queries attribute in the Android Manifest to support using external activities. By default Mendix provides actions for call, text and opening websites, hence these parameters are required.
> [MOO-396] Add tel query scheme for Android 11

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/build.gradle
Android 11 requires the Queries attribute in the Android Manifest to support using external activities. By default Mendix provides actions for call, text and opening websites, hence these parameters are required.
> [MOO-396] Add queries attribute to Android

- android/app/src/main/AndroidManifest.xml
add google.navigation scheme to android manifest for android 11 support.
> [NC-590]: Add support for google navigation

- android/build.gradle
Fixes compilation errors because latest version was used which broke the build.
> Pin androidXAnnotation and androidXBrowser version

- android/build.gradle
Jitpack has been down multiple times now and jcenter has caused issues in the past. We are adding cached fallback repositories for when this happens again.
> [MOO-905] Add cached maven repos to repository list

- CHANGELOG.md
- android/app/src/main/AndroidManifest.xml
Added the com.google.android.gms.permission.AD_ID permission to the manifest file. This permission is initially disabled to prevent unnecessary access to the user's advertising ID. If the app integrates ads, the tools:node="remove" attribute will need to be removed to facilitate ad personalization and tracking capabilities.
> [MOO-1017]: Adding Conditional Advertising ID Permission to Android Manifest

- CHANGELOG.md
- android/app/src/main/AndroidManifest.xml
Updated androidManifest to support open url with links to websites whose apps are installed on the device.
> [MOO-1257]: Update androidManfist to fix openUrl action error

- .github/workflows/release-it.yml
release-it versions above 16 dropped the support for node 16 we are using.
> Fix release-it version

- CHANGELOG.md
- android/app/src/main/java/com/mendix/nativetemplate/MainApplication.java
- ios/Podfile.lock
- patches/react-native+0.70.7.patch
App crashes were fixed by accessing registerReceiver via Context.
> [MOO-1620] fix app crashes for Android 34

- package-lock.json
- package.json
Upgrade mendix/native version to address native binary version mismatch issue
Studio Pro 10.24 expects NATIVE_BINARY_VERSION to be 14 for OTA to work correctly. Current @mendix/native(v9.0.4) has NATIVE_BINARY_VERSION=13. Released another version of @mendix/native(v9.0.6) with NATIVE_BINARY_VERSION=14 and integrating same here.
- If documentation update is not …
> Upgrade mendix/native version
